import { Content } from './types';

export const MOCK_CONTENT: Content[] = [
  {
    id: '1',
    title: 'Cosmic Odyssey',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    thumbnailUrl: 'https://picsum.photos/seed/c1/300/450',
    backdropUrl: 'https://picsum.photos/seed/b1/1280/720',
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    rating: 'PG-13',
    releaseYear: 2024,
    featured: true,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  },
  {
    id: '2',
    title: 'Cyber City Run',
    description: 'In a dystopian future, a young hacker uncovers a corporate conspiracy that could change the world.',
    thumbnailUrl: 'https://picsum.photos/seed/c2/300/450',
    backdropUrl: 'https://picsum.photos/seed/b2/1280/720',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    rating: 'R',
    releaseYear: 2023,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  },
  {
    id: '3',
    title: 'The Last Kingdom',
    description: 'A historical drama about the Viking invasion of England and the birth of a new nation.',
    thumbnailUrl: 'https://picsum.photos/seed/c3/300/450',
    backdropUrl: 'https://picsum.photos/seed/b3/1280/720',
    genre: ['History', 'Drama', 'Action'],
    rating: 'TV-MA',
    releaseYear: 2022,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  },
  {
    id: '4',
    title: 'Midnight Whispers',
    description: 'A detective with a troubled past hunts a serial killer who leaves cryptic clues at every crime scene.',
    thumbnailUrl: 'https://picsum.photos/seed/c4/300/450',
    backdropUrl: 'https://picsum.photos/seed/b4/1280/720',
    genre: ['Horror', 'Mystery', 'Thriller'],
    rating: 'R',
    releaseYear: 2021,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  },
  {
    id: '5',
    title: 'Laugh Riot',
    description: 'A group of friends embark on a disastrous road trip that tests their patience and their sanity.',
    thumbnailUrl: 'https://picsum.photos/seed/c5/300/450',
    backdropUrl: 'https://picsum.photos/seed/b5/1280/720',
    genre: ['Comedy'],
    rating: 'PG-13',
    releaseYear: 2024,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  },
  {
    id: '6',
    title: 'Ocean\'s Depths',
    description: 'A marine biologist discovers a new, intelligent species deep in the Mariana Trench, with unforeseen consequences.',
    thumbnailUrl: 'https://picsum.photos/seed/c6/300/450',
    backdropUrl: 'https://picsum.photos/seed/b6/1280/720',
    genre: ['Sci-Fi', 'Horror'],
    rating: 'PG-13',
    releaseYear: 2020,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  },
  {
    id: '7',
    title: 'The Gilded Cage',
    description: 'A period drama exploring the lives and scandals of high society in 19th-century New York.',
    thumbnailUrl: 'https://picsum.photos/seed/c7/300/450',
    backdropUrl: 'https://picsum.photos/seed/b7/1280/720',
    genre: ['Drama', 'Romance'],
    rating: 'TV-14',
    releaseYear: 2023,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  },
  {
    id: '8',
    title: 'Mountain\'s Fury',
    description: 'An experienced climber must rescue a group of stranded hikers from a deadly blizzard on K2.',
    thumbnailUrl: 'https://picsum.photos/seed/c8/300/450',
    backdropUrl: 'https://picsum.photos/seed/b8/1280/720',
    genre: ['Action', 'Adventure'],
    rating: 'PG-13',
    releaseYear: 2022,
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    trailerUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
  },
];